### ISSUE TITLE
Buchserstrasse is only a stub

### ISSUE THREAD

**Issue by habi** [EqualStreetNames/equalstreetnames-bern#8]
While discussing Zurich.EqualStreetNames we found that https://www.openstreetmap.org/way/122977868/ is not shown on https://bern.equalstreetnames.eu/

Let's investigate why.

**Comment by habi** [comment]
Maybe because it's a relation; https://www.openstreetmap.org/relation/2995406 ?

I 'detected' that it's a relation through the new edit link: https://github.com/EqualStreetNames/equalstreetnames/issues/195#issuecomment-848696524 :)

**Comment by jbelien** [comment]
Yes, I confirm that the Wikidata reference is not displayed on <https://bern.equalstreetnames.eu/> because `name:etymology:wikidata=Q329490` is missing on the relation.

If there is a relation, it will always have "priority" on the ways that are members of that relation.

**Comment by habi** [comment]
With https://edit.equalstreetnames.eu/ I added the correct wikidata ID to the relation: https://www.openstreetmap.org/changeset/105632330

Let's see how it looks after the next update.

**Comment by chatelao** [comment]
Looks very good to me, thanks for the fix

![image](https://user-images.githubusercontent.com/2461532/120263855-d50cba80-c29c-11eb-8e09-e2e1c020453f.png)
